### ISSUE TITLE
Terminal doesn't "write"

### ISSUE THREAD

**Issue by acook** [vitorgalvao/custom-iterm-applescripts-for-alfred#14]
On my system (OSX 10.10.3 & iTerm 2.1.1) the new terminal opens but the text isn't inserted. When I replace the code `tell mysession to write text q` with `tell the last session to write text q`, it works. So it seems that `mysession` isn't being set correctly.

**Comment by stuartcryan** [comment]
Hi acook,
That is unusual, can you please advise what happens if you change the line:
set mysession to (launch session \"Default Session\")
to:
set mysession to (make new session at the end of sessions)

and then use the original line:
tell mysession to write text q

Does that fix the problem?
Cheers,
Stuart

**Comment by chris838** [comment]
Similar problem. Using original script, a new iTerm tab opens but no command. If there are multiple panes open then I see the command in one of them, but nothing on the the new tab that has just opened.

set mysession to (make new session at the end of sessions)

Does not seem to do anything. However acook's suggestion does seem to work.

**Comment by phouse512** [comment]
@stuartcryan I also noticed this issue come up for me, running iTerm 2.1.4.  The issue (where the terminal opens but no command is run) would only happen if I had split a terminal into multiple panes in any other tab.  Running @acook 's suggestion worked for me.

Any idea what's up with this?  I will keep the change for now, but I wonder if anyone else has run into the issue and is stuck as well.

**Comment by stuartcryan** [comment]
Hi Everyone,
I have somewhat ceased development on the 2.1 branch as I moved over to the 2.9 branch long ago.

How many of you are still using 2.1 (as I will then have to assess if I throw some more work at diagnosing the issue further and testing the proposed workaround).
Cheers,
Stuart

**Comment by acook** [comment]
I'm on the 2.9 branch and everything seems to be working fine now with the latest script.

**Comment by vitorgalvao** [comment]
Issue seems to no longer be relevant, so closing. Please open a new issue if you still have this problem.

I’ll be introducing a new script version soon, so we’ll work from there to diagnose the problem if it still exists.
